name       : netdata
version    : 1.6.0
release    : 2
source     :
    - https://github.com/firehol/netdata/releases/download/v1.6.0/netdata-1.6.0.tar.xz : 7839491f6e8b297cc8c28ca96845ff087f7961a12b92aa0eea1f66528da8bdaf
license    : GPL-3.0
component  : network.utils
summary    : Real-time performance monitoring, done right
description: |
    netdata is the fastest way to visualize metrics. It is a resource
    efficient, highly optimized system for collecting and visualizing any
    type of realtime timeseries data, from CPU usage, disk activity, SQL
    queries, API calls, web site visitors, etc.

    netdata tries to visualize the truth of now, in its greatest detail,
    so that you can get insights of what is happening now and what just
    happened, on your systems and applications.
builddeps  :
    - pkgconfig(libmnl)
setup      : |
    %autogen --with-zlib --with-math --with-user=netdata
build      : |
    %make
install    : |
    %make_install
    find  $installdir/ -name .keep -delete
    install -dm00644 $installdir/etc/netdata/
    install -Dm00644 $pkgfiles/netdata.conf $installdir/etc/netdata/netdata.conf
    # Install netdata systemd stuff
    install -Dm00644 $pkgfiles/netdata.service $installdir/%libdir%/systemd/system/netdata.service
    install -Dm00644 $pkgfiles/netdata.sysusers $installdir/%libdir%/sysusers.d/netdata.conf
    install -Dm00644 $pkgfiles/netdata.tmpfiles $installdir/%libdir%/tmpfiles.d/netdata.conf
