name       : netdata
version    : 1.29.3
release    : 7
source     :
    - https://github.com/netdata/netdata/releases/download/v1.29.3/netdata-v1.29.3.tar.gz : eeba8b18519a9123a3cc8b450dcd042e23a3b145a78a7017a14c47ed36d923df
license    : GPL-3.0-or-later
component  : network.utils
summary    : Real-time performance monitoring, done right
description: |
    netdata is the fastest way to visualize metrics. It is a resource efficient, highly optimized system for collecting and visualizing any type of realtime timeseries data, from CPU usage, disk activity, SQL queries, API calls, web site visitors, etc.

    netdata tries to visualize the truth of now, in its greatest detail, so that you can get insights of what is happening now and what just happened, on your systems and applications.
builddeps  :
    - pkgconfig(libmnl)
    - pkgconfig(libuv)
setup      : |
    %configure --disable-cloud
build      : |
    %make
install    : |
    %make_install
    find  $installdir/ -name .keep -delete
    install -dm00644 $installdir/etc/netdata/
    install -Dm00644 $pkgfiles/netdata.conf $installdir/etc/netdata/netdata.conf
    # Install netdata systemd stuff
    install -Dm00644 $pkgfiles/netdata.service $installdir/%libdir%/systemd/system/netdata.service
    install -Dm00644 $pkgfiles/netdata.sysusers $installdir/%libdir%/sysusers.d/netdata.conf
    install -Dm00644 $pkgfiles/netdata.tmpfiles $installdir/%libdir%/tmpfiles.d/netdata.conf
